package xeadDriver;

/*
 * Copyright (c) 2014 WATANABE kozo <qyf05466@nifty.com>,
 * All rights reserved.
 *
 * This file is part of XEAD Driver.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the XEAD Project nor the names of its contributors
 *       may be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

public class Res_ja extends java.util.ListResourceBundle {
	private static final Object[][] contents = new String[][]{
		{ "Add", "登録" },
		{ "Asterisk", "＊" },
		{ "ByteaFieldMessage1", "コンテンツの表示" },
		{ "ByteaFieldMessage2", "ファイルのアップロード" },
		{ "ByteaFieldMessage3", "コンテンツのクリア" },
		{ "ByteaFieldMessage4", "バイナリデータの処理オプション" },
		{ "ByteaFieldMessage5", "格納されているデータについて、処理を選択してください。" },
		{ "ByteaFieldMessage6", "アップロードファイルを指定してください。" },
		{ "ByteaFieldMessage7", "アップロード" },
		{ "ByteaFieldMessage8", "拡張子が不明なため、アップロードできません。" },
		{ "ByteaFieldMessage9", "アップロードに失敗しました。エラー：" },
		{ "ByteaFieldMessage10", "内容が空、またはファイルタイプが不明なため、データを表示できません。" },
		{ "ByteaFieldMessage11", "データを表示できません。エラー：" },
		{ "Calendar", "営業カレンダー" },
		{ "CalendarComment", "上下左右矢印=選択日を移動、Shift+左右矢印=月を移動\nEnter=選択日を返す、Ctrl+P=直接入力、Ctrl+9=最大値を返す" },
		{ "CalendarMessage1", "日付を直接入力してください。" },
		{ "CalendarMessage2", "日付が正しくありません。" },
		{ "Cancel", "キャンセル" },
		{ "CheckBoxOnTableHeader", "チェックすれば全行選択されます" },
		{ "CheckToContinue", "処理継続の確認" },
		{ "CheckToDelete", "削除の確認" },
		{ "ChrossCheck", "クロスチェック中" },
		{ "Close", "閉じる" },
		{ "Colon", "：" },
		{ "Continue", "継続する" },
		{ "DBConnectMessage1", "セッションを強制終了する" },
		{ "DBConnectMessage2", "再接続する" },
		{ "DBConnectMessage3", "データベースにアクセスできません。回線状態を確認してください。" },
		{ "DBConnectMessage4", "データベースへの再接続の確認" },
		{ "Descend", "(降順)" },
		{ "DialogCheckReadContinue", "残りを続けてスキャンする" },
		{ "DialogCheckReadCountUnit", "読取行数" },
		{ "DialogCheckReadMessage1", "" },
		{ "DialogCheckReadMessage2", "件目から" },
		{ "DialogCheckReadMessage3", "件目までがスキャンされ、そのうちの" },
		{ "DialogCheckReadMessage4", "件が選択されています。" },
		{ "DialogCheckReadMessage5", "後続処理を指定してください。" },
		{ "DialogCheckReadNextRow", "読取開始行" },
		{ "DialogCheckReadRestart", "開始行指定で再スキャンする" },
		{ "DialogCheckReadTitle", "読取条件の確認" },
		{ "Edit", "編集" },
		{ "Exit", "終了する" },
		{ "ExitButton", "終了" },
		{ "ExplosionAsRoot", "ルートとして正展開" },
		{ "FunctionError0", "ログイン・スクリプトにおいてエラーが発生しました。セッションは開始されません。" },
		{ "FunctionError1", "テーブル「" },
		{ "FunctionError2", "」のスクリプト「" },
		{ "FunctionError3", "」に含まれる" },
		{ "FunctionError4", "... に相当するフィールド定義が見つかりません" },
		{ "FunctionError5", "エラーが発生しました。処理はキャンセルされます。\nエラーの詳細については、セッションログで確認してください。" },
		{ "FunctionError6", "ＳＱＬエラー。処理はキャンセルされます。\nエラーの詳細については、セッションログで確認してください。" },
		{ "FunctionError7", "「" },
		{ "FunctionError8", "」のスクリプトエラー。処理はキャンセルされます。\nエラーの詳細については、セッションログで確認してください。" },
		{ "FunctionError9", "＊指定された機能(" },
		{ "FunctionError10", ")の定義が見つかりません。処理は中断されました。" },
		{ "FunctionError11", "が見つかりません" },
		{ "FunctionError12", "機能定義内のスクリプトにおいてエラーが発生しました。処理はキャンセルされます。\nエラーの詳細については、セッションログで確認してください。" },
		{ "FunctionError13", "＊明細処理機能(" },
		{ "FunctionError14", ")の仕様情報が見つかりません。" },
		{ "FunctionError15", "＊要求された機能は実行されませんでした。" },
		{ "FunctionError16", "何らかの値を入力してください。" },
		{ "FunctionError17", "＊ボタンにリンクされた機能(" },
		{ "FunctionError18", ")の仕様情報が見つかりません。" },
		{ "FunctionError19", "＊データを読み取って更新するまでの間に他のセッションによって更新されたか、\n読取専用ＤＢに対して更新要求がなされたため、処理はキャンセルされました。" },
		{ "FunctionError20", "＊バッチレコードを追加できませんでした。\n更新操作はキャンセルされました。" },
		{ "FunctionError21", "＊データを更新できません。" },
		{ "FunctionError22", "＊既存データと重複します。別の値を指定してください。" },
		{ "FunctionError23", "正しい値を指定してください。" },
		{ "FunctionError24", "" },
		{ "FunctionError25", "の区分定義が存在しません。" },
		{ "FunctionError26", "＊" },
		{ "FunctionError27", "行目のキー値が変更されているため、更新できません。" },
		{ "FunctionError28", "＊" },
		{ "FunctionError29", "行目について他の行との値の重複があります。値を変更してください。" },
		{ "FunctionError30", "選択されたデータが現時点で存在しません。処理はキャンセルされます。" },
		{ "FunctionError31", "＊同一のキー値を持つデータが既に存在しています。値を変更してください。" },
		{ "FunctionError32", "＊キー値は変更できません。" },
		{ "FunctionError33", "＊データを読み取って削除するまでの間に他のセッションによって更新されたか、\n読取専用ＤＢに対して削除要求がなされたため、処理はキャンセルされました。" },
		{ "FunctionError34", "＊このデータを前提とする別のデータが存在しているため、削除できません。" },
		{ "FunctionError35", "関連する" },
		{ "FunctionError36", "が見つかりません。" },
		{ "FunctionError37", "＊指定されたキー値を持つデータが存在しません。" },
		{ "FunctionError38", "選択されたデータは現時点で処理できません。" },
		{ "FunctionError39", "フレーズ式'" },
		{ "FunctionError40", "'の設定が正しくありません。" },
		{ "FunctionError41", "＊見出し処理機能(" },
		{ "FunctionError42", ")の仕様情報が見つかりません。" },
		{ "FunctionError43", "＊見出しテーブルのキー値が変更されたため、明細行を処理できません。" },
		{ "FunctionError44", "＊削除すべき明細行が選択されていません。" },
		{ "FunctionError45", "データが存在しません。" },
		{ "FunctionError46", "の絞込み条件を指定値で正しく初期化できません。" },
		{ "FunctionError47", "必須の検索条件「" },
		{ "FunctionError48", "」が指定されていません。" },
		{ "FunctionError49", "会計日として処理可能な範囲からはずれています。" },
		{ "FunctionError50", "＊読取専用ＤＢに対して追加要求がなされたため、処理はキャンセルされました。" },
		//{ "FunctionError51", "＊読取専用テーブルに対して更新操作できません。処理はキャンセルされました。" },
		{ "FunctionError52", "＊行追加リストに表示カラムが指定されていません。処理はキャンセルされます。" },
		{ "FunctionError53", "指定値にもとづく" },
		{ "FunctionMessage1", "＊絞込み条件を指定して検索ボタン(Ctrl+L)を押してください。" },
		{ "FunctionMessage2", "＊一覧上の行を矢印キー(↑↓)で選択してEnterキーを押してください。各列の欄見出しをクリックすれば列値順に並び替えされます。" },
		{ "FunctionMessage3", "＊一覧上の行を矢印キー(↑↓)で選択してEnterキーを押せば、詳細を確認できます。各列の欄見出しをクリックすれば列値順に並び替えされます。" },
		{ "FunctionMessage4", "＊絞込み条件に一致するデータは見つかりませんでした。" },
		{ "FunctionMessage5", "＊必要に応じて明細行をチェック(v)して、「" },
		{ "FunctionMessage6", "」を押してください。" },
		{ "FunctionMessage7", "＊必要に応じて各項目の値を編集して、「" },
		{ "FunctionMessage8", "」を押してください。Enterキーでエラー検査のみがなされます。" },
		{ "FunctionMessage9", "＊エラーはありません。更新してください。" },
		{ "FunctionMessage10", "" },
		{ "FunctionMessage11", "の詳細確認" },
		{ "FunctionMessage12", "＊必要に応じてボタンを押してください。" },
		{ "FunctionMessage13", "" },
		{ "FunctionMessage14", "の追加" },
		{ "FunctionMessage15", "＊必要に応じて値を入力して、登録ボタンを押してください。" },
		{ "FunctionMessage16", "＊エラーはありません。登録してください。" },
		{ "FunctionMessage17", "新たな" },
		{ "FunctionMessage18", "が追加されました。登録作業を終了しますか？" },
		{ "FunctionMessage19", "＊必要に応じて値を修正して、登録ボタンを押してください。" },
		{ "FunctionMessage20", "＊レコードは追加されましたが、追加後に起動されるべき機能(" },
		{ "FunctionMessage21", ")が見つかりません。" },
		{ "FunctionMessage22", "" },
		{ "FunctionMessage23", "の編集" },
		{ "FunctionMessage24", "＊必要に応じて値を入力して更新してください。Enterキーでエラー検査のみがなされます。" },
		{ "FunctionMessage25", "" },
		{ "FunctionMessage26", "の複写" },
		{ "FunctionMessage27", "このデータを" },
		{ "FunctionMessage28", "します。よろしいですか？" },
		{ "FunctionMessage29", "＊キー値を入力して「OK」を押してください。" },
		{ "FunctionMessage30", "＊明細タブとボタンが定義されていません。" },
		{ "FunctionMessage31", "＊明細データは見つかりませんでした。" },
		{ "FunctionMessage32", "＊行を選択してエンターしてください。" },
		{ "FunctionMessage33", "＊明細行の追加操作は取り消されました。" },
		{ "FunctionMessage34", "＊キー値の重複のため、" },
		{ "FunctionMessage35", "件が追加されませんでした。" },
		{ "FunctionMessage36", "選択されている明細行(No." },
		{ "FunctionMessage37", ")を削除します。よろしいですか？" },
		{ "FunctionMessage38", "が開始されました。" },
		{ "FunctionMessage39", "＊明細行は削除されませんでした。" },
		{ "FunctionMessage40", "件の" },
		{ "FunctionMessage41", "が更新されました。" },
		{ "FunctionMessage42", "が更新され、" },
		{ "FunctionMessage43", "が登録されました。" },
		{ "FunctionMessage44", "指定時刻に処理が実行されます。スタートを押して待機状態にしてください。" },
		{ "FunctionMessage45", "にセットされました。このダイアログを閉じるかストップを押せば、タイマーは解除されます。" },
		{ "FunctionMessage46", "タイマーが解除されました。" },
		{ "FunctionMessage47", "処理が開始されました。" },
		{ "FunctionMessage48", "処理が正常に終了しました。" },
		{ "FunctionMessage49", "＊選択可能な" },
		{ "FunctionMessage50", "が見つかりませんでした。" },
		{ "FunctionMessage51", "処理が異常終了しました。" },
		{ "FunctionMessage52", "＊追加された行を編集してください。" },
		{ "FunctionMessage53", "WEBサービスを利用できません。ネット接続を確認してください。" },
		{ "FunctionMessage54", "郵便番号の値が無効です。" },
		{ "FunctionMessage55", "ログアウトしますか？                      " },
		{ "FunctionMessage56", "の並び順で一覧されます。Shiftキーを使えば逆順に一覧されます。" },
		{ "FunctionMessage57", "＊検索結果を確認してください。各列の欄見出しをクリックすれば列値順に並び替えされます。" },
		{ "FunctionMessage58", "明細キーである「" },
		{ "FunctionMessage59", "」の値を指定してください。" },
		{ "FunctionMessage60", "＊明細行は追加されませんでした。" },
		{ "FunctionMessage61", "入出力ファイルの指定 " },
		{ "FunctionMessage62", "指定の日時値 '" },
		{ "FunctionMessage63", "' が正しくないため、\nこの検索条件は無視されます。 " },
		{ "Iconify", "最小化" },
		{ "ImageFileMessage1", "規定外のファイル形式です。<br>クリックすれば画像表示されます" },
		{ "ImageFileNotFound1", "<html>指定された画像ファイル<br>" },
		{ "ImageFileNotFound2", "<br>が見つかりません" },
		{ "ImageFileShown", "クリックすれば別画面で全体表示されます。" },
		{ "Implosion", "逆展開" },
		{ "ImplosionAsRoot", "ルートとして逆展開" },
		{ "InputImageFileName", "画像ファイル名を入力してください" },
		{ "JavaVersionError1", "Javaのバージョンが " },
		{ "JavaVersionError2", " であるためにXEAD Editorを起動できません。\n規定のバージョンは1.6.*～1.7.*です。" },
		{ "LineNumber1", "(" },
		{ "LineNumber2", "行目)：" },
		{ "LogIn", "ログイン" },
		{ "LogInComment", "ユーザＩＤとパスワードを入力してください。" },
		{ "LogInError1", "現在、このユーザＩＤは無効です。" },
		{ "LogInError2", "ユーザＩＤかパスワードが正しくありません。" },
		{ "LogInError3", "現在、ログインできません。システム管理者に確認してください。" },
		{ "LogInError4", "LOGIN_PERMITTEDのシステム変数が登録されていないため、ログインできません。システム管理者に確認してください。" },
		{ "LogInError5", "KBCALENDARのユーザ変数が登録されていないため、ログインできません。システム管理者に確認してください。" },
		{ "LogOut", "ログアウト" },
		{ "MinusError", "この項目でのマイナス符号は無視されます。" },
		{ "Modify", "変更" },
		{ "ModifyPassword", "パスワードの変更" },
		{ "ModifyPasswordError1", "新しいパスワードは５～１０桁としてください。" },
		{ "ModifyPasswordError2", "変更できません。現行パスワード\nが正しくない可能性があります。" },
		{ "ModifyPasswordError3", "新しいパスワードの２つの値が一致しません。" },
		{ "Next", "次へ" },
		{ "No", "いいえ" },
		{ "NumberFormatError", "小数点は入力できません。" },
		{ "Password", "パスワード" },
		{ "PasswordCurrent", "パスワード(現)" },
		{ "PasswordModified", "＊パスワードが変更されました。" },
		{ "PasswordNew", "パスワード(新)" },
		{ "ReferCheckerMessage0", "＊" },
		{ "ReferCheckerMessage1", "" },
		{ "ReferCheckerMessage2", "行目に関して、" },
		{ "ReferCheckerMessage3", "このデータを参照する「" },
		{ "ReferCheckerMessage4", "」との間で不整合が生じるため、登録は許可されません。詳しくはセッションログを参照してください。" },
		{ "ReferCheckerMessage5", "このデータを参照する「" },
		{ "ReferCheckerMessage6", "」との間で不整合が生じるため、更新は許可されません。詳しくはセッションログを参照してください。" },
		{ "ReferCheckerMessage7", "このデータを参照する「" },
		{ "ReferCheckerMessage8", "」との間で不整合が生じるため、削除は許可されません。詳しくはセッションログを参照してください。" },
		{ "ReferCheckerMessage9", "＊関連レコード(" },
		{ "ReferCheckerMessage10", ")との間で不整合が生じるため、この更新は許可されません。" },
		{ "Refresh", "再表示" },
		{ "ReturnMessage00", "＊処理は正常に完了しました。" },
		{ "ReturnMessage01", "＊処理は取り消されました。" },
		{ "ReturnMessage10", "＊データは正常に登録されました。" },
		{ "ReturnMessage11", "＊登録処理は取り消されました。" },
		{ "ReturnMessage20", "＊データは正常に更新されました。" },
		{ "ReturnMessage21", "＊更新処理は取り消されました。" },
		{ "ReturnMessage30", "＊データは正常に削除されました。" },
		{ "ReturnMessage31", "＊削除操作は取り消されました。" },
		{ "ReturnMessage99", "＊処理が異常終了しました。セッション情報のエラーログを確認してください。" },
		{ "Search", "検索" },
		{ "Sel", "選" },
		{ "SessionError1", "システム定義ファイルが指定されていません。処理は終了します。" },
		{ "SessionError2", "指定ファイル " },
		{ "SessionError3", " をＸＭＬデータとしてパースできません。処理は取り消されます。" },
		{ "SessionError4", "データベースサービスが開始されていないため、" },
		{ "SessionError5", "を起動できません。" },
		{ "SessionError6", "データベース " },
		{ "SessionError7", " に接続できませんでした。\n" },
		{ "SessionError8", "印刷用フォント " },
		{ "SessionError9", " の指定が正しくありません。デフォルトのPDFフォント(Times-Roman)が代入されました。" },
		{ "SessionError10", "XEAD Editorを用いて、社内連絡用ページ等のＵＲＬを指定してください。ただし、スタイルシートやスクリプトを用いた高度なページは扱えません" },
		{ "SessionError11", "指定されたページ " },
		{ "SessionError12", " を開けません。" },
		{ "SessionError13", "指定されている採番キーの値 " },
		{ "SessionError14", " が採番テーブル上に見つかりません。" },
		{ "SessionError15", "指定された機能の仕様が見つかりません。" },
		{ "SessionError16", "" },
		{ "SessionError17", "用のヘルプページが指定されていません。" },
		{ "SessionError18", "" },
		{ "SessionError19", "用のメニューのヘルプページを開けません。\n" },
		{ "SessionError20", "これ以上の再帰呼び出しを避けるため、この機能は利用\nできません。要求は取り消されます。" },
		{ "SessionError21", "指定ファイル " },
		{ "SessionError22", " が存在しません。処理は取り消されます。" },
		{ "SessionMessage1", "＊矢印キーで機能ボタンを選択し、Enterしてください。Ｆ１２でログイン・パスワードを変更できます。" },
		{ "SessionMessage2", "＊矢印キーで機能ボタンを選択し、Enterしてください。Ｆ１で業務マニュアルが表示され、Ｆ１２でログイン・パスワードを変更できます。" },
		{ "SplashMessage0", "XEAD Driverを起動中..." },
		{ "SplashMessage1", "システム定義を分析中..." },
		{ "SplashMessage2", "メニューをロード中..." },
		{ "SplashMessage3", "クロスチェッカーをロード中... " },
		{ "SplashMessage4", "機能をロード中... " },
		{ "TimerCondition", "実行条件" },
		{ "TimerError", "実行時刻の指定が正しくありません。処理は実行されませんでした。" },
		{ "TimerStart", "スタート" },
		{ "TimerStop", "ストップ" },
		{ "TimerTime", "実行時刻" },
		{ "TimerRepeat", "到来の度に実行" },
		{ "TimerRunNow", "即時実行" },
		{ "TimerRunOffDay", "休日でも実行" },
		{ "Total", "合計" },
		{ "Update", "更新" },
		{ "URLFont", "ＭＳ 明朝" },
		{ "UserID", "ユーザＩＤ" },
		{ "UserName", "ユーザ名" },
		{ "XLSComment1", "＊データがエクセルシートに出力されました。" },
		{ "XLSComment2", "＊この一覧は次の条件で絞込まれています：" },
		{ "XLSErrorMessage", "エクセルデータの出力エラーが発生しました。エラーの詳細については、セッションログで確認してください。" },
		{ "Yes", "はい" }
	};

	public Object[][] getContents() {
		return contents;
	}
}